[tool.poetry]
name = "pyspark"
version = "0.0.1"
description = "pyspark related development"
authors = ["Benjamin Du <longendu@yahoo.com>"]

[tool.poetry.dependencies]
python = ">=3.7"
loguru = ">=0.5.1"

[tool.poetry.dev-dependencies]
pyspark = ">=3.0.1"
pyspark-stubs = ">=3.0.0"
pytest = ">=6.2.0"
pylint = ">=2.5.3"
pytype = { version = ">=2020.08.10", python = "<3.9" }
yapf = ">=0.30.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
