[tool.poetry]
name = "pyspark"
version = "0.0.1"
description = "pyspark related development"
authors = ["Benjamin Du <longendu@yahoo.com>"]

[tool.poetry.dependencies]
python = ">=3.6"
loguru = "^0.5.1"

[tool.poetry.dev-dependencies]
pyspark = "^3.0.0"
pyspark-stubs = ">=3.0.0"
pylint = "^2.5.3"
pytest = "^5.4.3"
mypy = ""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
