[tool.poetry]
name = "name_of_your_project"
version = "0.1.0"
description = "Description of your project."
authors = ["Benjamin Du <longendu@yahoo.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.9"
loguru = ">=0.5.3"
pyarrow = ">=2.0.0"
pandas = ">=1.2.1"

[tool.poetry.dev-dependencies]
pyspark = ">=3.0.1"
pyspark-stubs = ">=3.0.0"
findspark = ">=1.4.2"
pytest = ">=6.2.0"
pylint = ">=2.5.3"
pytype = { version = ">=2020.08.10", python = "<3.9" }
yapf = ">=0.30.0"
ipykernel = ">=5.5.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
